import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '~/styles/Home.module.css'

export default function AboutPage (): JSX.Element {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Link href="/">
          Home
        </Link>
        <div className={styles.description}>
          <h1>About Page</h1>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

      </main>
    </>
  )
}
